# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:9102/music/lyric?scaleId=0
Accept: */*
Keep-Alive: True
Cache-Control: no-cache

###
GET http://localhost:9102/music/lyric?scaleId=1
Accept: */*
Keep-Alive: True
Cache-Control: no-cache

###
GET http://localhost:9102/music/lyric?scaleId=10
Accept: */*
Keep-Alive: True
Cache-Control: no-cache


###
GET http://localhost:9102/music/lyric?scaleId=100
Accept: */*
Keep-Alive: True
Cache-Control: no-cache

###
GET http://localhost:9102/music/lyric?scaleId=-1
Accept: */*
Keep-Alive: True
Cache-Control: no-cache


###
GET http://localhost:8000/world
Accept: */*
Cache-Control: no-cache
